package io.jpress.module.entre.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.entre.model.base.BaseAreaManage;

/**
 * Generated by JPress.
 */
@Table(tableName = "area_manage", primaryKey = "id")
public class AreaManage extends BaseAreaManage<AreaManage> {

    private static final long serialVersionUID = 1L;

	
}
