package io.jpress.module.entre.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAreaManage<M extends BaseAreaManage<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setAreaCode(java.lang.String areaCode) {
		set("area_code", areaCode);
	}
	
	public java.lang.String getAreaCode() {
		return getStr("area_code");
	}

	public void setAreaName(java.lang.String areaName) {
		set("area_name", areaName);
	}
	
	public java.lang.String getAreaName() {
		return getStr("area_name");
	}

}
